### ISSUE TITLE
Support global configuration file for storing definitions and layer state locally

### ISSUE THREAD

**Issue by lucasfcosta** [ergomake/layerform#14]
- [ ] Support writing a config file in the `.layerform` directory
- [ ] Layerform CLI should read from this file to know where to store configs _locally_

Example:

```yml
currentContext: my-s3-context
contexts:
  my-local-context:
    type: local
    dir: folder-a # this can be relative to this file or absolute
```
