### ISSUE TITLE
Add a command to select the current context

### ISSUE THREAD

**Issue by vieiralucas** [ergomake/layerform#89]
Introduce a new command `layerform config use-context <name>` that will change the `current` selected context:

For example, if we have a config file like this:
```yaml
currentContext: foo
contexts:
    bar:
        type: local
        dir: test
    baz:
        type: local
        dir: test
    foo:
        type: s3
        bucket: bucket
        region: us-east-1
```

Current context is `foo`

Running `layerform config use-context bar`, should set the current context to `bar`, changing the config file to:
```yaml
currentContext: bar
contexts:
    bar:
        type: local
        dir: test
    baz:
        type: local
        dir: test
    foo:
        type: s3
        bucket: bucket
        region: us-east-1
```
