### ISSUE TITLE
Ability to read definitions from an S3 bucket

### ISSUE THREAD

**Issue by lucasfcosta** [ergomake/layerform#9]
- [ ] Support writing a config file in the `.layerform` directory (file name is `configurations.yml`)
- [ ] Support setting current context in the same file
- [ ] Now, user manually uploads definitions to this place (currently a `json`)
- [ ] S3 bucket is all ours, we'll override file if it exists.

Example:

```yml
currentContext: my-s3-context
contexts:
  my-s3-context:
    type: s3
    bucket: blabla
  my-local-context:
    type: local
    dir: folder-a # this can be relative to this file or absolute
```
